### ISSUE TITLE
move Actions 

### ISSUE THREAD

**Issue by mtahir08** [mtahir08/bootcamp_project_05#17]
move submit handlers to Auth Action files
![image](https://user-images.githubusercontent.com/8261297/76167308-7e8efa00-6187-11ea-91d4-b17d893fdf45.png)

**Comment by mtahir08** [comment]
Also use general handler for email and pass

**Comment by umairmustafa753** [comment]
sir I moved fetch functions to action and made general handler and push files in authreducer branch
